version: 2.1
machine:
  timezone: UTC

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8

defaults: &defaults
  working_directory: ~/jt-web
  docker:
    - image: circleci/openjdk:11.0.3-stretch
      environment:
        - SBT_VERSION: 1.2.8

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          checkout: false
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: "${AWS_RESOURCE_NAME_PREFIX}-int"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/update-service:
          family: "${AWS_RESOURCE_NAME_PREFIX}-service-int"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster-int"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service-int,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${AWS_RESOURCE_NAME_PREFIX}-int:${CIRCLE_SHA1}"
          verify-revision-is-deployed: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
